# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lep', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='whFaction',
            field=models.TextField(verbose_name='faction'),
        ),
    ]
