# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lep', '0004_auto_20170219_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.TextField(default='Członek', verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='member',
            name='whFaction',
            field=models.TextField(default='Brak', verbose_name='faction'),
        ),
    ]
